### ISSUE TITLE
Sending `true` (bool) using Symfony's VarDumper shows as `false` in bugregator UI

### ISSUE THREAD

**Issue by FluffyDiscord** [buggregator/frontend#11]
![image](https://github.com/buggregator/server/assets/10332247/118924e1-4512-49ba-b71e-321474e2311e)

![image](https://github.com/buggregator/server/assets/10332247/a0b1b58a-3261-4ddc-9fd1-9aae39f23f77)

**Comment by Kreezag** [comment]
Fixed in [662b7a0](https://github.com/buggregator/frontend/commit/662b7a0df566726856cb3bece3c98eb93136b4c4)

Will be available in next release.

**Comment by FluffyDiscord** [comment]
Amazing, thank you

**Comment by butschster** [comment]
Problem is not solved(
Here are correct payloads for `true` and `false` values

```json
// true
"payload": {
    "type": "boolean",
    "value": "1"
},
```

```json
// fakse
"payload": {
    "type": "boolean",
    "value": ""
},
```
